### ISSUE TITLE
manifest的定义存在一些问题

### ISSUE THREAD

**Issue by hankxdev** [chokcoco/del_ad_chrome_ext#1]
算是一点最佳实践：

1: browser_action 是不需要的，因为一点功能都没有，就显示一个静态的Clear success？不要增加不必要的浏览器元素。
2：permission也是不需要的，因为在content_script中已经定义了。不做CROS，不动态注入的话，不需要申请网址permission
3：content_scripts中的matches值可简写为“_://_/_”， 其他网址的定义就更不需要了。只要有了_://_/_，就是对所有网址都生效，无需再申明其他网址匹配。
4：content_scripts还可添加一项“run_at”:"document_end"，这样注入的文件就会在文档节点加载完以后就开始执行，否则默认会等所有资源都加载完才执行。

**Comment by zhaoaaaaa5** [comment]
@HangYang 第二条不需要是不是因为content_scripts里面的matches已经说明了？

**Comment by hankxdev** [comment]
@zhaoaaaaa5 并不是，permission中的URL定义是为了做CROS或者动态注入来用的。这个和content_script并无必然联系。而这个扩展并不需要做这些。
